[project]
name = "music-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
